added sway apps mako swaylock and enhanced sway dbus activation for xdg-desktop-portal. Moreover mpd - pipewire - pulseaudio integration begins to work properly

diff --git a/.config/waybar/bin/void-power b/.config/waybar/bin/void-power
--- a/.config/waybar/bin/void-power
+++ b/.config/waybar/bin/void-power
@@ -1,23 +1,26 @@
 #!/bin/sh
 
-cmd=$1
+cmd="${1}"
 
-case $cmd in
-poweroff)
-  notify-send "Poweroff signal received"
-  dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.STOP
-  ;;
-reboot)
-  nofify-send "Reboot signal received"
-  dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.RESTART
-  ;;
-suspend)
-  dbus-send --system --print-repky --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend
-  ;;
-hibernate)
-  dbus-send --system --print-repky --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Hibernate
-  ;;
-*)
-  echo "Illegal state"
+case "${cmd}" in
+  poweroff)
+    notify-send "Poweroff signal received"
+    dbus-send --system --print-reply --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Manager.PowerOff boolean:true
+    ;;
+  reboot)
+    nofify-send "Reboot signal received"
+    dbus-send --system --print-reply --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Manager.Reboot boolean:true
+    ;;
+  suspend)
+    dbus-send --system --print-repky --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Suspend boolean:true
+    ;;
+  hibernate)
+    dbus-send --system --print-repky --dest="org.freedesktop.login1" /org/freedesktop/login1 org.freedesktop.login1.Hibernate boolean:true
+    ;;
+  *)
+    printf "%s\n" "Invalid argument"
+    exit 22
+    ;;
 esac
 
+exit 0
